-- MySQL Script generated by MySQL Workbench
-- Thu Nov  7 16:08:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema P3Database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `P3Database` ;

-- -----------------------------------------------------
-- Schema P3Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `P3Database` DEFAULT CHARACTER SET utf8 ;
USE `P3Database` ;

-- -----------------------------------------------------
-- Table `P3Database`.`time_slots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P3Database`.`time_slots` ;

CREATE TABLE IF NOT EXISTS `P3Database`.`time_slots` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `StartTime` TIME NOT NULL,
  `EndTime` TIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `id_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P3Database`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P3Database`.`students` ;

CREATE TABLE IF NOT EXISTS `P3Database`.`students` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UMID` INT NOT NULL,
  `FirsName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `EmailAddress` VARCHAR(45) NULL,
  `TimeSlotId` INT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `UMID_UNIQUE` (`UMID` ASC) VISIBLE,
  INDEX `student_time_slot_idx` (`TimeSlotId` ASC) VISIBLE,
  CONSTRAINT `student_time_slot`
    FOREIGN KEY (`TimeSlotId`)
    REFERENCES `P3Database`.`time_slots` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
